### ISSUE TITLE
Delete a valid room throws 500 internal error

### ISSUE THREAD

**Issue by Salvatore-tech** [Salvatore-tech/SmartHome#21]
The error could be seen **after applying the patch related to validations** done after deleting a room.
If passing an invalid room id the result is correctly 404 Not Found, on the other hand if passing a valid room id it's thrown a 500 internal error.

- **Url** (invalid room) : http://localhost:{{Port}}/room/deleteRoom/FAKE_ROOM
- **Response**: 404 Not Found

- **Url** (valid room): http://localhost:{{Port}}/room/deleteRoom/ZUQJ-9281
- **Response**:
 {
    "timestamp": "2021-08-21T17:21:23.444+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/room/deleteRoom/ZUQJ-9281"
}

**Comment by Salvatore-tech** [comment]
Update: the internal error is caused by a foreign key violation on the DB underneight:

- 2021-08-22 01:28:38.589 ERROR 6956 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERRORE: l'istruzione UPDATE o DELETE sulla tabella "room" viola il vincolo di chiave esterna "fk8nnipnjiephps7atqdnvmfndp" sulla tabella "device"

It's not allowed to remove an entity (Room) referenced by another one (Device) without defining a strategy for updating the foreign key value. 
Needs further investigation on how to update it and about cascade types

**Comment by pizza11x** [comment]
Check to confirm
