### ISSUE TITLE
Delete Device throws 500 internal error

### ISSUE THREAD

**Issue by Salvatore-tech** [Salvatore-tech/SmartHome#36]
ERROR 11344 --- [nio-8080-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERRORE: l'istruzione UPDATE o DELETE sulla tabella "device" viola il vincolo di chiave esterna "conditions_device_id_fkey" sulla tabella "conditions"

  Dettaglio: La chiave (id)=(PCRM-6254) è ancora referenziata dalla tabella "conditions".

org.postgresql.util.PSQLException: ERRORE: l'istruzione UPDATE o DELETE sulla tabella "device" viola il vincolo di chiave esterna "conditions_device_id_fkey" sulla tabella "conditions"

**Comment by antoniocolucci** [comment]
Now, with the postman request for deleteDevice, we can delete the device from the device table and the condition from the conditions table without errors.
