### ISSUE TITLE
Delete a Room throws 500 internal error 

### ISSUE THREAD

**Issue by Salvatore-tech** [Salvatore-tech/SmartHome#37]
ERRORE: l'istruzione UPDATE o DELETE sulla tabella "room" viola il vincolo di chiave esterna "device_room_id_fkey" sulla tabella "device"
  Dettaglio: La chiave (id)=(XUZC-2250) è ancora referenziata dalla tabella "device".

Similar to https://github.com/Salvatore-tech/SmartHome/issues/36#issue-1046285253

**Comment by pizza11x** [comment]
Issue solved, setting the devices associated with the room you want to delete with the Default room and then subsequently deleting the room.
The update is not wrong.
