### ISSUE TITLE
Fix FindDeviceInScene: 500 Internal Server Error.

### ISSUE THREAD

**Issue by antoniocolucci** [Salvatore-tech/SmartHome#50]
Error: Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: class com.gruppo1.smarthome.model.Conditioner cannot be cast to class com.gruppo1.smarthome.crud.memento.Memento (com.gruppo1.smarthome.model.Conditioner and com.gruppo1.smarthome.crud.memento.Memento are in unnamed module of loader 'app'); nested exception is com.fasterxml.jackson.databind.JsonMappingException: class com.gruppo1.smarthome.model.Conditioner cannot be cast to class com.gruppo1.smarthome.crud.memento.Memento (com.gruppo1.smarthome.model.Conditioner and com.gruppo1.smarthome.crud.memento.Memento are in unnamed module of loader 'app')]

**Comment by pizza11x** [comment]
You have to use the objectMapper, to print the list of objects (see in the device controller in "findAll")
